config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :categories
  resources :comments
  resources :enclosures
  resources :episodes
  resources :podcasts, param: :slug
  resources :posts, param: :slug
  resources :tags

end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast
  belongs_to :post
  belongs_to :author, class_name: User.to_s, foreign_key: :user_id
  belongs_to :user
  has_one :enclosure
  
  # validates :enclosure, presence: true
  
  after_save :update_podcast_rss_feed!, if: :has_enclosure? # this should never fire since the relationship exists on the enclosure and I create the enclosure after the episode.
  
  module EpisodeTypes
    FULL = "full"
    TRAILER = "trailer"
    BONUS = "bonus"
  end
  
  def self.where_podcast_id(podcast_id = [])
    self.where(podcast_id: podcast_id)
  end
  
  def self.where_post_id(post_id = [])
    self.where(post_id: post_id)
  end
  
  def update_podcast_rss_feed!
    podcast.create_rss_feed!(upload: Rails.env.production?)
  end
  
  # def production_ready?
  #   enclosure.present? && post.state == Post::States::PUBLISHED
  # end
  
  def has_enclosure?
    enclosure.present?
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # before_action :authenticate_user, only: [:create, :update, :destroy]

  def index
    @episodes = Episode.all.order(created_at: :desc)
  end
  
  def show
    @episode = Episode.find(params[:id])
  end

  def new
    @episode = Episode.new
  end

  def edit
    @episode = Episode.find(params[:id])
  end
  
  def create
    number = Episode.all.map(&:number).max + 1
    guid = SecureRandom.uuid
    if @episode = Episode.create!(episode_params.merge({number: number, guid: guid}))
      redirect_to episode_url(@episode), notice: "Episode was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def update
    @episode = Episode.find(params[:id])
    if @episode.update!(episode_params)
      redirect_to episode_url(@episode), notice: "Episode was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    episode = Episode.find(params[:id])
    episode.destroy!
    redirect_to episode_url, notice: "Episode was successfully deleted."
  end
  
  private
  
  def episode_params
    permitted = [:title, :guid, :summary, :number, :episode_type, :duration, :explicit, :image, :podcast_id, :post_id, 
      :user_id, :created_at, :updated_at]
    params.require(:episode).permit(*permitted)
  end
end

app/views/episodes/_episode.html.erb
<div id="<%= dom_id episode %>">
    <p><%= episode.title %></p>
</div>

app/views/episodes/_form.html.erb
<%= form_with model: episode do |form| %>
    <% if episode.errors.any? %>
        <div style="color: red">
            <h2>
                <%= pluralize episode.errors.count, "error"%> prohibited this episode from being saved:
            </h2>
            <ul>
                <% episode.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :summary, style: "display: block" %>
        <%= form.text_area :summary %>
    </div>
    <div>
        <%= form.label :episode_type, style: "display: block" %>
        <%= form.select :episode_type, Episode::EpisodeTypes.constants %>
    </div>
    <div>
        <%= form.label :duration, style: "display: block" %>
        <%= form.text_field :duration %>
    </div>
    <div>
        <%= form.check_box :explicit %>
        <%= form.label :explicit, style: "display: block" %>
    </div>
    <div>
        <%= form.label :image, style: "display: block" %>
        <%= form.text_field :image %>
    </div>
    <div>
        <%= form.label :podcast, style: "display: block" %>
        <%= form.select :podcast_id, Podcast.all.map{|p| [p.title, p.id]} %>
    </div>
    <div>
        <%= form.label :post_id %>
        <%= form.text_field :post_id %>
    </div>
    <div>
        <%= form.label :user, style: "display: block" %>
        <%= form.select :user_id, User.all.map{|u| [u.full_name, u.id]} %>
    </div>

    <%= form.submit %>
<% end %>

app/views/episodes/edit.html.erb
<h1>Edit Episode</h1>

<%= render "form", episode: @episode %>

<%= link_to "Back to episodes", episodes_path %>

app/views/episodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Episodes</h1>

<div id="episodes">
  <% @episodes.each do |episode| %>
    <%= render episode %>
    <p>
      <%= link_to "Show this episode", episode_path(episode) %>
    </p>
  <% end %>
</div>

<%= link_to "New episode", new_episode_path %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
    <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/show.html.erb
<p style="color: green"><%= notice %></p>
<h3><%= @episode.title %></h3>
<p><%= @episode.number %></p>
<p><%= @episode.summary %></p>
<%= link_to "Edit", edit_episode_path(@episode) %>
<%= button_to "Delete", @episode, method: :delete %>
<%= link_to "Back to episodes", episodes_path %>