config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :categories
  resources :comments
  resources :enclosures
  resources :episodes
  resources :podcasts, param: :slug
  resources :posts, param: :slug
  resources :tags

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # before_action :authenticate_user, only: [:create, :update, :destroy]

  def index
    @tags = Tag.all.order(id: :desc)
  end
  
  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end
  
  def create
    @tag = Tag.create!(tag_params)
    if @tag
      redirect_to tag_url(@tag), notice: "Tag was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to tag_url(@tag), notice: "Tag was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy!
    redirect_to tags_url, notice: "Tag was successfully deleted."
  end  
  private
  
  def tag_params
    params.require(:tag).permit(:name, :created_at, :updated_at)
  end
end

app/views/tags/_form.html.erb
<%= form_with model: tag do |form| %>
    <% if tag.errors.any? %>
        <div style="color: red">
            <h2>
                <%= pluralize tag.errors.count, "error"%> prohibited this tag from being saved:
            </h2>
            <ul>
                <% tag.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
    </div>

    <%= form.submit %>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
    <p><%= tag.name %></p>
</div>

app/views/tags/edit.html.erb
<h1>Edit Tag</h1>

<%= render "form", tag: @tag %>

<%= link_to "Back to tags", tags_path %>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
    <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p>name: <%= @tag.name %></p>
<%= link_to "Edit", edit_tag_path(@tag) %>
<%= button_to "Delete", @tag, method: :delete %>
<%= link_to "Back to tags", tags_path %>