config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

  resources :categories
  resources :comments
  resources :enclosures
  resources :episodes
  resources :podcasts, param: :slug
  resources :posts, param: :slug
  resources :tags

end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :author, class_name: User.to_s, foreign_key: :user_id
  belongs_to :user
  has_many :episodes
  
  module PodcastTypes
    EPISODIC = "episodic"
    SERIAL = "serial"
  end

  def to_param
    slug
  end
  
  def self.where_state(states = [])
    self.where(state: states)
  end

  def explicit_str
    explicit == true ? "yes" : "no"
  end
  
  def create_rss_feed!(upload: false)
    rss = Tempfile.new
    rss << <<-HEREDOC
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>#{CGI::escapeHTML(title)}</title>
    <link>#{website}</link>
    <language>en-us</language>
    <copyright>&#169; #{Time.now.year} #{author.pen_name}</copyright>
    <itunes:author>#{author.pen_name}</itunes:author>
    <description>#{CGI::escapeHTML(description)}</description>
    <itunes:type>#{podcast_type}</itunes:type>
    <itunes:owner>
      <itunes:name>#{author.pen_name}</itunes:name>
      <itunes:email>#{author.email}</itunes:email>
    </itunes:owner>
    <itunes:image href="#{File.join(Rails.configuration.cdn_url, image)}"/>
    <itunes:category text="#{CGI::escapeHTML(category)}">
      <itunes:category text="#{CGI::escapeHTML(subcategory)}"/>
    </itunes:category>
    <itunes:explicit>#{explicit}</itunes:explicit>
      HEREDOC
      
    episodes.joins(:post).where(posts: {state: Post::States::PUBLISHED}).order("posts.published_at DESC").each do |episode|
      rss << <<-HEREDOC
    <item>
      <itunes:episodeType>#{episode.episode_type}</itunes:episodeType>
      <itunes:episode>#{episode.number}</itunes:episode>
      <title>#{CGI::escapeHTML(episode.title)}</title>
      <itunes:title>#{CGI::escapeHTML(episode.title)}</itunes:title>
      <description>#{CGI::escapeHTML(episode.summary)}</description>
      <itunes:summary><![CDATA[#{CGI::escapeHTML(episode.summary)}]]></itunes:summary>
      <enclosure 
        length="#{episode.enclosure.size}" 
        type="#{episode.enclosure.mime_type}" 
        url="#{File.join(Rails.configuration.cdn_url, episode.enclosure.url)}"
      />
      <link>#{File.join(Rails.configuration.web_url, "posts", episode.post.slug)}</link>
      <guid>#{episode.guid}</guid>
      <pubDate>#{episode.post.published_at.rfc2822}</pubDate>
      <itunes:duration>#{episode.duration}</itunes:duration>
      <itunes:explicit>#{episode.explicit}</itunes:explicit>
    </item>
        HEREDOC
    end
      
    rss << <<-HEREDOC
  </channel>
</rss>
      HEREDOC
    
    if upload
      rss.close
      target = File.join(title.parameterize, "#{title.parameterize}.xml")
      S3Api.upload_file!(rss.path, target)
      rss.open
    end
    
    rss.rewind
    puts rss.read
    rss.close
    
    rss.unlink
  end

  def apple_podcasts_link
    "https://podcasts.apple.com/us/podcast/#{self.slug}/id#{self.external_id}"
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  # before_action :authenticate_user, only: [:create, :update, :destroy]
  
  def index
    @podcasts = Podcast.all.order(created_at: :desc)
  end
  
  def show
    @podcast = Podcast.find_by_slug(params[:slug])
  end

  def new
    @podcast = Podcast.new
  end

  def edit
    @podcast = Podcast.find_by_slug(params[:slug])
  end
  
  def create
    if @podcast = Podcast.create!(podcast_params.merge({user_id: 1}))
      redirect_to podcast_url(@podcast), notice: "Podcast was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def update
    @podcast = Podcast.find_by_slug(params[:slug])
    if @podcast.update!(podcast_params)
      redirect_to podcast_url(@podcast), notice: "Podcast was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    podcast = Podcast.find_by_slug(params[:slug])
    podcast.destroy!
    redirect_to podcast_url, notice: "Podcast was successfully deleted."
  end
  
  private
  
  def podcast_params
    permitted = [:title, :description, :website, :podcast_type, :feed, :image, :category, :subcategory, :explicit, 
      :created_at, :updated_at, :slug, :state, :header_image, :external_id]
    params.require(:podcast).permit(*permitted)
  end
end

app/views/podcasts/_form.html.erb
<%= form_with model: podcast do |form| %>
    <% if podcast.errors.any? %>
        <div style="color: red">
            <h2>
                <%= pluralize podcast.errors.count, "error"%> prohibited this podcast from being saved:
            </h2>
            <ul>
                <% podcast.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_area :description %>
    </div>
    <div>
        <%= form.label :website, style: "display: block" %>
        <%= form.text_field :website %>
    </div>
    <div>
        <%= form.radio_button :podcast_type, Podcast::PodcastTypes::EPISODIC %>
        <%= form.label :podcast_type, "Episodic" %>
        <%= form.radio_button :podcast_type, Podcast::PodcastTypes::SERIAL %>
        <%= form.label :podcast_type, "Serial" %>
    </div>
    <div>
        <%= form.label :feed, style: "display: block" %>
        <%= form.text_field :feed %>
    </div>
    <div>
        <%= form.label :image, style: "display: block" %>
        <%= form.text_field :image %>
    </div>
    <div>
        <%= form.label :category, style: "display: block" %>
        <%= form.text_field :category %>
    </div>
    <div>
        <%= form.label :subcategory, style: "display: block" %>
        <%= form.text_field :subcategory %>
    </div>
    <div>
        <%= form.check_box :explicit %>
        <%= form.label :explicit %>
    </div>
    <div>
        <%= form.label :slug, style: "display: block" %>
        <%= form.text_field :slug %>
    </div>
    <div>
        <%= form.label :state, style: "display: block" %>
        <%= form.select :state, Post::States.constants %>
    </div>
    <div>
        <%= form.label :header_image, style: "display: block" %>
        <%= form.text_field :header_image %>
    </div>
    <div>
        <%= form.label :external_ID, style: "display: block" %>
        <%= form.text_field :external_ID %>
    </div>

    <%= form.submit %>
<% end %>

app/views/podcasts/_podcast.html.erb
<div id="<%= dom_id podcast %>">
    <p><%= podcast.title %></p>
</div>

app/views/podcasts/edit.html.erb
<h1>Edit Podcast</h1>

<%= render "form", podcast: @podcast %>

<%= link_to "Back to podcasts", podcasts_path %>

app/views/podcasts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Podcasts</h1>

<div id="podcasts">
  <% @podcasts.each do |podcast| %>
    <%= render podcast %>
    <p>
      <%= link_to "Show this podcast", podcast_path(podcast) %>
    </p>
  <% end %>
</div>

<%= link_to "New podcast", new_podcast_path %>

app/views/podcasts/new.html.erb
<h1>New Podcast</h1>

<%= render "form", podcast: @podcast %>

<br>

<div>
    <%= link_to "Back to podcasts", podcasts_path %>
</div>

app/views/podcasts/show.html.erb
<p style="color: green"><%= notice %></p>
<h3><%= @podcast.title %></h3>
<%= link_to "Edit", edit_podcast_path(@podcast) %>
<%= button_to "Delete", @podcast, method: :delete %>
<%= link_to "Back to podcasts", podcasts_path %>